###

### post to stream
POST http://localhost:20001
Content-Type: application/json

{
  "info": "this is test"
}

### post to custom stream


POST http://localhost:20002
Content-Type: application/json

{
  "id": "123aaadddd",
  "info": "this is test custom"
}