server:
  port: 8761
#spring:
#  application:
#    name: discovery-service
eureka:
  instance:
    hostname: localhost
  dashboard:
    enabled: true
    path: /dash
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    root: DEBUG